### PR TITLE
chore: update for the latest

### PR DESCRIPTION
**Pull request by YohannParis**
# Description

Change the TERArium deployment to download `latest` and not `0.0.0` anymore

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Nithos — APPROVED** [review]
This looks good, just a quick note on K8s Image Pull policy as it may need to be communicated to the team.

```
There are three image policy pull options for Kubernetes. 
- If imagePullPolicy is set to Always, Kubernetes will always pull the image from the Repository. 
- With IfNotPresent, Kubernetes will only pull the image when it does not already exist on the node. 
- While with imagePullPolicy set to Never, Kubernetes will never pull the image. 

If the above is not explicitly set it will derive its policy based on the tag as per the following:
- If the image is tagged latest, then Kubernetes will assume the imagePullPolicyto be Always.
- An image with no tag is assumed to be latest, and so its policy is set to Always. 
- Otherwise, the orchestrator will default the imagePullPolicy to IfNotPresent. 
```

So with this change K8s will always try to pull the latest image when launching. SO make sure devs have set up the secret keys appropriately (and set them for k8s) as otherwise the pulls will fail even there is a local version present.

**Comment by YohannParis** [comment]
> This looks good, just a quick note on K8s Image Pull policy as it may need to be communicated to the team.
> 
> ```
> There are three image policy pull options for Kubernetes. 
> - If imagePullPolicy is set to Always, Kubernetes will always pull the image from the Repository. 
> - With IfNotPresent, Kubernetes will only pull the image when it does not already exist on the node. 
> - While with imagePullPolicy set to Never, Kubernetes will never pull the image. 
> 
> If the above is not explicitly set it will derive its policy based on the tag as per the following:
> - If the image is tagged latest, then Kubernetes will assume the imagePullPolicyto be Always.
> - An image with no tag is assumed to be latest, and so its policy is set to Always. 
> - Otherwise, the orchestrator will default the imagePullPolicy to IfNotPresent. 
> ```
> 
> So with this change K8s will always try to pull the latest image when launching. SO make sure devs have set up the secret keys appropriately (and set them for k8s) as otherwise the pulls will fail even there is a local version present.

I think it's a good thing, a kind of play by fire, to make sure they always have their tokens working, etc.
I will update the documentation to add this information though.
@dgauldie what do you think?

**Review by dgauldie — APPROVED** [review]
LGTM

**Comment by dgauldie** [comment]
I agree that this is the behaviour that we want

**Pull request merged**
