### PR TITLE
feat: 64 task refactor and cleanup deployment scripts

### PR DESCRIPTION
**Pull request by dgauldie**
# Description

Please include a summary of the changes and the related issue.

Resolves #(issue)

### CODE REVIEW

**Review by YohannParis — COMMENTED** [review]
Why not put all the `hmi-*` into one kustomization?

**Comment by bigglesandginger** [comment]
> Why not put all the `hmi-*` into one kustomization?

This will allow starting the entire stack and then stopping just `hmi-client` or whatever.  If both server and client were in the one kustomization.yaml then it would be impossible to stop just the client (etc).  The Gateway can live as one kustomization as it never needs to be just one thing (though you will notice the database has been pulled out for local work - as it is not needed in staging and production).

This looks complicated at first, but once we get used to this it will become much more friendly - when working with an environment you will only need to see the things that are unique to that environment.  That is the idea.

**Comment by YohannParis** [comment]
Local deployment keycloack isn't happy.

Screen Shot 2023-01-24 at 11 47 51

**Review by bigglesandginger — APPROVED** [review]
dev and staging working

**Pull request merged**
